block-nuggets: 54

ores:
  DEEPSLATE:
    SILICON_NUGGET: 0.61
    ALUMINUM_NUGGET: 0.15
    POTASSIUM_NUGGET: 0.09
    SULFUR_NUGGET: 0.06
    IRON_NUGGET: 0.04
    MAGNESIUM_NUGGET: 0.02
    CARBON_PIECE: 0.01

    OTHER: 0.02

  DIORITE:
    SILICON_NUGGET: 0.51
    ALUMINUM_NUGGET: 0.09
    SODIUM_NUGGET: 0.09
    CALCIUM_NUGGET: 0.08
    POTASSIUM_NUGGET: 0.08
    SULFUR_NUGGET: 0.03
    ZIRCONIUM_NUGGET: 0.03
    IRON_NUGGET: 0.02
    MAGNESIUM_NUGGET: 0.02
    TITANIUM_NUGGET: 0.01
    NEODYMIUM_NUGGET: 0.01
    ZINC_NUGGET: 0.01

    OTHER: 0.02

  ANDESITE:
    SILICON_NUGGET: 0.55
    SODIUM_NUGGET: 0.10
    CALCIUM_NUGGET: 0.09
    POTASSIUM_NUGGET: 0.08
    ZIRCONIUM_NUGGET: 0.07
    ALUMINUM_NUGGET: 0.03
    SULFUR_NUGGET: 0.03
    IRON_NUGGET: 0.01
    MAGNESIUM_NUGGET: 0.01
    ZINC_NUGGET: 0.01

    OTHER: 0.02

  GRANITE:
    SILICON_NUGGET: 0.35
    IRON_NUGGET: 0.28
    SULFUR_NUGGET: 0.27
    ZINC_NUGGET: 0.04
    TIN_NUGGET: 0.02
    ZIRCONIUM_NUGGET: 0.01
    GOLD_NUGGET: 0.009
    PURE_URANIUM_NUGGET: 0.001

    OTHER: 0.02

  CALCITE:
    SILICON_NUGGET: 0.33
    CALCIUM_NUGGET: 0.17
    SODIUM_NUGGET: 0.09
    POTASSIUM_NUGGET: 0.08
    CARBON_PIECE: 0.08
    COPPER_NUGGET: 0.07
    SULFUR_NUGGET: 0.06
    IRON_NUGGET: 0.03
    ZINC_NUGGET: 0.02
    TIN_NUGGET: 0.02

    OTHER: 0.05

  BASALT:
    SILICON_NUGGET: 0.65
    CARBON_PIECE: 0.15
    SULFUR_NUGGET: 0.10
    GOLD_NUGGET: 0.05

    OTHER: 0.05

  TUFF:
    SILICON_NUGGET: 0.65
    ALUMINUM_NUGGET: 0.25
    CARBON_PIECE: 0.04
    TIN_NUGGET: 0.01

    OTHER: 0.05

  BLACKSTONE:
    SILICON_NUGGET: 0.50
    CARBON_PIECE: 0.25
    SULFUR_NUGGET: 0.13
    GOLD_NUGGET: 0.07

    OTHER: 0.05

  NETHERRACK:
    SILICON_NUGGET: 0.45
    SULFUR_NUGGET: 0.40

    OTHER: 0.15

  CLAY:
    SILICON_NUGGET: 0.35
    ALUMINUM_NUGGET: 0.20
    MAGNESIUM_NUGGET: 0.20
    POTASSIUM_NUGGET: 0.06
    CALCIUM_NUGGET: 0.06
    SODIUM_NUGGET: 0.06
    IRON_NUGGET: 0.05
    CARBON_PIECE: 0.01

    OTHER: 0.01

  DIRT:
    SILICON_NUGGET: 0.45
    ALUMINUM_NUGGET: 0.30
    CARBON_PIECE: 0.15

    OTHER: 0.10

  SAND:
    SILICON_NUGGET: 0.95

    OTHER: 0.05

  RED_SAND:
    SILICON_NUGGET: 0.85
    IRON_NUGGET: 0.10

    OTHER: 0.05

other-percentages:
  SILICON_NUGGET: 2000
  ALUMINUM_NUGGET: 1000
  SODIUM_NUGGET: 500
  CALCIUM_NUGGET: 450
  POTASSIUM_NUGGET: 350
  MAGNESIUM_NUGGET: 200
  SULFUR_NUGGET: 150
  ZINC_NUGGET: 100
  TIN_NUGGET: 70
  IRON_NUGGET: 50
  ZIRCONIUM_NUGGET: 40
  COPPER_NUGGET: 20
  GOLD_NUGGET: 10
  CARBON_PIECE: 1
  NEODYMIUM_NUGGET: 0.5
  PURE_URANIUM_NUGGET: 0.1



